### ISSUE TITLE
Calendar Plus no longer detects when calendar gets disabled

### ISSUE THREAD

**Issue by solomonswise** [maxpatiiuk/calendar-plus#246]
Hello
I love Calendar Plus, and I have a feature request.
I would like to be able to exclude certain calendars from the graphs etc that Calendar Plus produces. I'm sure that would be a very useful feature for many people. In my case, it's necessary because I have a number of calendars which provide guides for me but don't represent actual time spent on anything. For example I have a 'bookable appointments' calendar with entries in every day, which I use to show me which time slots I'm making available for work with my clients. It's just a guide - it never represents something actual. So in order for the Calendar Plus information to make sense, I need to be able to exclude it (and a number of other calendars too). I've tried to figure out if this is possible in the current calendar plus but I can't see any way to do it.
My preferred way - much as changing between day/week/month/year changes the overlay's data, I'd find it very useful if only those calendars which are checked 'for display' in my google calendar contributed to the statistics.
Would this be possible?
Thank you
Justin Wise

**Comment by maxpatiiuk** [comment]
> My preferred way - much as changing between day/week/month/year changes the overlay's data, I'd find it very useful if only those calendars which are checked 'for display' in my google calendar contributed to the statistics.

This exact feature was implemented, but it appears to have broken down.
I will be away from my laptop for a bit, but would like to look into fixing this once I am back.
Thanks for bringing this to my attention

**Comment by solomonswise** [comment]
Thank you for responding to this so quickly!
I can see it's fixed.
I am so very grateful for this wonderful extension.
Justin
--
Justin Wise
wearethirdspace.org | podcast turningtowards.life | writing justinwise.co.uk


I check my emails twice per day, mid morning and mid afternoon.
If you need me urgently please message me by text or whatsapp.
